//this file can be run on an AWS instance by itself
version: "3"

services:
  app:
    container_name: tdomingo/moreplaces
    restart: on-failure
    build: .
    ports:
      - 3004:3004
    links:
      - mongo
    command: sh -c 'npm run dock'

  mongo:
    container_name: tdomingo/mongo
    image: mongo
    ports:
      - "27017:27017"
